Agree to terms: true
Are you a US citizen?: "Yes"
Are you comfortable commuting to this job's location?: "Yes"
Are you comfortable working in an onsite setting?: "Yes"
Are you willing to undergo a background check, in accordance with local law/regulations?: "Yes"
By clicking 'I acknowledge,' you agree to our Privacy Policy and data processing.:
  I
  acknowledge
Confirm that you understand this is a Contract position and not a staff permanent role?: "Yes"
Did you submit a 5-10 min video of your proudest coding project to Dropbox, named as FirstnameLastnameMobile.mp4?: "No"
Do you have a disability?: "No"
Do you have at least 5 years of professional experience in full-stack development?: "Yes"
Do you require sponsorship?: "No"
"Have you completed the following level of education: Master's Degree?": "No"
How many years of work experience do you have with Amazon Web Services (AWS)?: "5"
How many years of work experience do you have with CI/CD frameworks?: "3"
How many years of work experience do you have with Containerization?: "3"
How many years of work experience do you have with DevOps?: "3"
How many years of work experience do you have with Django?: "3"
How many years of work experience do you have with Hydrogen?: "1"
How many years of work experience do you have with Infrastructure as code (IaC)?: "3"
How many years of work experience do you have with Java?: "2"
How many years of work experience do you have with Orchestration?: "3"
How many years of work experience do you have with Python (Programming Language)?: "5"
How many years of work experience do you have with React.js?: "2"
How many years of work experience do you have with Shopify?: "3"
LinkedIn Profile: https://www.linkedin.com/in/samuelclark/
? Our position is funded by a U.S. National Science Foundation (NSF) grant, which
  requires specific citizenship criteria. Are you a U.S. citizen or permanent resident?
: "Yes"
Phone country code: United States (+1)
Website: NA
