3 years in working with EHR systems: "No"
5+ years of relevant work experience in software development: true
AWS Data Engineer: "2"
Able to start in 2 weeks: "Yes"
Address: Miami, Florida, United States
"Address: City, State & Zip Code": Miami, Florida, United States
"Address: Line 1": Miami, Florida, United States
"Address: Line 2": Miami, Florida, United States
Agree to terms: true
? Applicants MUST currently be located in either Eastern Standard or Central Standard
  Time Zones. Do you currently live in the Eastern or Central Standard Time Zones?
: "Yes"
Are you 18 or older?: "yes"
? "Are you 18 or older?

  Are you 18 or older?"
: "Yes"
Are you a C2C candidate?: "No"
? "Are you a U.S. Citizen or Green Card holder? \nAre you a U.S. Citizen or Green\
  \ Card holder?"
: "Yes"
Are you a U.S. Citizen?: "Yes"
Are you a US Citizen or Green Card Holder?: "Yes"
Are you a US Citizen or Green Card currently living in the United States and able to work W2 as a VALERE Employee?: "Yes"
Are you a US citizen or a Green Card Holder?: "Yes"
Are you a US citizen?: "Yes"
Are you a United States Citizen or Permanent Resident/Full GC Holder?: "Yes"
Are you a United States Citizen?: "Yes"
