5+ years of relevant work experience in software development: true
Address: Miami, Florida, United States
"Address: City, State & Zip Code": Miami, Florida, United States
"Address: Line 1": Miami, Florida, United States
"Address: Line 2": Miami, Florida, United States
Agree to terms: true
Are you a US citizen?: "Yes"
Are you a resident of North Carolina?: "No"
Are you a resident of the United States?: "Yes"
Are you authorized to lawfully work for Coalition in the country to which you are applying?: "Yes"
Are you comfortable commuting to this job's location?: "Yes"
? "Are you comfortable working in a remote setting?

  Are you comfortable working in a remote setting?

  Required"
: "Yes"
Are you comfortable working in an onsite setting?: "Yes"
Are you experienced within AI, Insurtech, Fintech or HealthTech?: "Yes"
Are you experienced within a start-up or scale-up environment?: "Yes"
Are you experienced working for a scale-up or start-up company?: "Yes"
Are you legally authorized to work in the United States?: "Yes"
? "Are you legally authorized to work in the United States?

  Are you legally authorized to work in the United States?

  Required"
: ""
Are you legally authorized to work in the United States? Required: "Yes"
? "Are you located in either the CST or EST time zones in the United States?

  Are you located in either the CST or EST time zones in the United States?"
: "Yes"
Are you physically located in the United States?: "Yes"
Are you proficient in Node.js, TypeScript, and React.js?: "Yes"
? "Are you willing to take a drug test, in accordance with local law/regulations?

  Are you willing to take a drug test, in accordance with local law/regulations?

  Required"
: ""
Are you willing to undergo a background check, in accordance with local law/regulations?: "Yes"
? "Are you willing to undergo a background check, in accordance with local law/regulations?

  Are you willing to undergo a background check, in accordance with local law/regulations?

  Required"
: ""
Based on the role, what is your salary requirement?: "125000"
By clicking "I acknowledge," you agree to our Privacy Policy and data processing:
  I
  acknowledge
? By clicking "I acknowledge," you agree to our Privacy Policy and data processing
  Providing accurate information is essential, as any dishonesty may lead to rejection
  of an application or termination
: "Yes"
City: Miami
Company Jobs Page: "Yes"
Confirm that you understand this is a Contract position and not a staff permanent role?: "Yes"
Current company: Freelance
Did an employee refer you to this opportunity? If so, what is their name?: "false"
Did you actually read our JD? (Answer is in the JD): no too long
Did you attend a "Blue Collar" college in USA or Canada for Computer Science?: "No"
Did you submit a 5-10 min video of your proudest coding project to Dropbox, named as FirstnameLastnameMobilemp4?: "No"
Disability Status: Not provided
? Do you have 4-5 years of experience in healthcare data adhering to FHIR, HL7 standards,
  and Epic clarity extracts, ensuring compliance with data regulations?
: "Yes"
Do you have a disability?: "No"
? Do you have a portfolio? A portfolio could be a Github repository, a personal website,
  document showcasing prior work, or an otherwise detailed description of tangible,
  individual contributions.
: "Yes"
Do you have at least 5 years of professional experience in full-stack development?: "Yes"
Do you have experience optimizing complex web application performance in Nextjs?: "2"
Do you have experience using Rust?: "false"
Do you have experience with Epic Professional Billing and Epic Hospital Billing?: "No"
Do you have experience with GDB debugging and command line tool experience?: "Yes"
Do you have experience with React within an e-commerce environment?: "true"
Do you have experience with SSR?: "false"
Do you have knowledge of RESTful APIs and integrating frontend applications with backend services?: "true"
Do you now or will you in the future require immigration sponsorship to work at Cloudflare?: "No"
? Do you now, or will you in the future, require employment visa sponsorship (eg,
  H-1B visa, renewals, etc) to work lawfully for Coalition in the country that you
  are applying to?
: "No"
Do you require sponsorship?: "No"
Familiarity with Microsoft Hyper-V virtualization technology is beneficial: "true"
Gender: Not provided
"Have you completed the following level of education: Bachelor's Degree?": "No"
? "Have you completed the following level of education: Bachelor's Degree?

  Have you completed the following level of education: Bachelor's Degree?

  Required"
: ""
"Have you completed the following level of education: Master's Degree?": "No"
Have you ever served in the military?: "false"
Have you ever worked for Coalition before?: "false"
? "Have you got any experience programming robot arms?

  Have you got any experience programming robot arms?"
: "No"
? "Have you got commercial experience working with robot camera calibration tools?

  Have you got commercial experience working with robot camera calibration tools?"
: "No"
? "Have you had any experience working in the music industry, or are you currently
  involved in it?

  Have you had any experience working in the music industry, or are you currently
  involved in it?"
: "No"
Have you mostly worked as Data scientist? (Please note that our customer looks for SWEs, not Data scientists): "false"
Have you worked in a software development or tech company environment? If so, how long?:
  5
  years
Headline: Software Developer with 5 years of experience
Highest Level of Education Completed: Some college
How did you hear about this job?: I heard about this job through a job search platform
? "How many years of AWS experience do you have?

  How many years of AWS experience do you have?"
: "5"
How many years of Angular experience do you have?: "2"
How many years of DynamoDB experience do you have?: "3"
How many years of Node experience do you have?: "2"
How many years of experience do you have in FinTech or Blockchain?: "2"
How many years of experience do you have with Python?: "5"
How many years of experience with React or Next do you have?: "3"
How many years of full-time industry experience do you have?: "3"
How many years of hands-on experience with Node or Nest do you have?: "2"
How many years of hands-on programming experience do you have in PHP?: "2"
How many years of professional experience do you have in programming in Go/Golang?: "2"
How many years of professional software engineering experience?: "5"
How many years of relevant professional working experience do you have?: "2"
How many years of start-up experience do you have?: "4"
How many years of work experience do you have with 3rd Party Integrations?: "2"
How many years of work experience do you have with Agile Environment?: "2"
How many years of work experience do you have with Amazon Bedrock?: "2"
How many years of work experience do you have with Amazon Web Services (AWS)?: "5"
How many years of work experience do you have with Angular?: "2"
How many years of work experience do you have with Apex Programming?: "2"
How many years of work experience do you have with Backbone.js?: "2"
How many years of work experience do you have with CI/CD frameworks?: "3"
How many years of work experience do you have with Computer Vision libraries?: "1"
How many years of work experience do you have with Computer Vision?: "1"
How many years of work experience do you have with Containerization?: "3"
How many years of work experience do you have with Crystal Reports?: "2"
How many years of work experience do you have with DevOps?: "3"
How many years of work experience do you have with Django?: "3"
How many years of work experience do you have with FastAPI?: "5"
How many years of work experience do you have with Git?: "2"
How many years of work experience do you have with Hydrogen?: "1"
How many years of work experience do you have with Infrastructure as code (IaC)?: "3"
How many years of work experience do you have with Java?: "2"
How many years of work experience do you have with Large Language Models (LLM)?: "2"
How many years of work experience do you have with Magento?: "1"
How many years of work experience do you have with MarkLogic?: "2"
How many years of work experience do you have with MongoDB?: "2"
How many years of work experience do you have with Node.js?: "3"
How many years of work experience do you have with Orchestration?: "3"
How many years of work experience do you have with Platform as a Service (PAAS)?: "3"
How many years of work experience do you have with Python (Programming Language)?: "5"
How many years of work experience do you have with React Hooks?: "2"
How many years of work experience do you have with Reactjs?: "2"
How many years of work experience do you have with Salesforce.com Development?: "2"
How many years of work experience do you have with SciPy?: "2"
How many years of work experience do you have with Shopify?: "3"
How many years of work experience do you have with XSLT?: "2"
? "I have contributed to the infra of a flow pipeline and can share my github contributions
  to this

  I have contributed to the infra of a flow pipeline and can share my github contributions
  to this"
: "No"
? If you were referred by a current employee, please provide their name here. If you
  were not referred by a current employee, please put N/A.
: N/A
Middle name: N/A
? Our position is funded by a US National Science Foundation (NSF) grant, which requires
  specific citizenship criteria Are you a US citizen or permanent resident?
: "Yes"
Phone country code: United States (+1)
Proficiency in programming languages, including C#, Python, React, NET, and PowerShell: "5"
School: Some college
? This position is remote for teammates based in North Carolina ideally, Raleigh/Durham/RTP
  area Are you located in North Carolina?
: "No"
Understanding of database systems and proficiency in SQL: 5 years
Veteran Status: "false"
? "We must fill this position urgently. Can you start immediately?

  We must fill this position urgently. Can you start immediately?

  Required"
: ""
Website: NA
? Were you referred to this position by an FHF employee? If yes, what is their name?
  If yes, do you reside with any currently employed FHF employee?
: "false"
What is your current location?: Miami, Florida, United States
What is your salary expectations?: "135000"
Which of the following best describes your gender?: Male
Which of the following best describes your racial or ethnic identity?:
  I prefer not
  to disclose
? Will you now or in the future require First Help Financial to commence ("sponsor")
  an immigration case in order to employ you (for example, H-1B or other employment-based
  immigration case)? This is sometimes called "sponsorship" for an employment-based
  visa status
: "false"
? "Will you now, or in the future, require sponsorship for employment visa status
  (e.g. H-1B visa status)?

  Will you now, or in the future, require sponsorship for employment visa status (e.g.
  H-1B visa status)?

  Required"
: ""
Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? Required: "No"
Would you like to include your LinkedIn profile, personal website or blog?: "false"
have you had experience with Angular 12+?: "Yes"
